LIBFT_A=libft/libft.a

all : ok

$(LIBFT_A):
	$(MAKE) -C libft 

ok:
	cc applyexp.c parsing.c match_advance.c constructors.c libft.a
g:
	cc applyexp.c parsing.c match_advance.c constructors.c libft.a -g
